version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    command: bash -c "yarn install && yarn dev"
    container_name: gogollellero_client